spring.application.name=app
spring.datasource.url=jdbc:mysql://localhost:3306/online_food_delivery_db
spring.datasource.username=root
spring.datasource.password=Mysql@1234

spring.profiles.active=dev
#spring.profiles.active=prod

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

logging.level.org.mybatis=DEBUG
logging.level.org.springframework.jdbc=DEBUG
mybatis.configuration.map-underscore-to-camel-case=true